<template>
  <div v-if="isOpen" class="modal-overlay" @click="closeModal">
    <div class="modal modal-large" @click.stop>
      <div class="modal-header">
        <h3>추가변경</h3>
        <button class="modal-close" @click="closeModal">
          <i class="fas fa-times"></i>
        </button>
      </div>

      <div class="modal-body">
        <!-- 변경 사유 입력 -->
        <div class="form-section">
          <label class="form-label required">변경 사유</label>
          <textarea
            v-model="changeReason"
            class="form-textarea"
            rows="3"
            placeholder="변경 사유를 입력하세요 (필수)"
          ></textarea>
        </div>

        <!-- 품목별 수량 변경 -->
        <div class="form-section">
          <div class="section-header">
            <label class="form-label">품목별 수량 변경</label>
            <button
              type="button"
              class="btn-add-item"
              disabled
              title="품목 추가는 출하 등록 시에만 가능합니다"
            >
              <i class="fas fa-plus"></i>
              품목 추가
            </button>
          </div>
          <div class="table-container">
            <table class="data-table">
              <thead>
                <tr>
                  <th class="col-item-name">품목명</th>
                  <th class="col-spec col-spec-header">규격</th>
                  <th class="col-quantity">현재수량</th>
                  <th class="col-quantity">변경수량</th>
                  <th class="col-diff">차이</th>
                  <th class="col-action">삭제</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="item in editableItems" :key="item.skuId" :class="{ 'new-item-row': item.isNew }">
                  <td class="col-item-name">
                    <span v-if="item.isNew" class="badge-new">신규</span>
                    {{ item.itemName }}
                  </td>
                  <td class="col-spec" :title="item.specification || '-'">{{ formatSpecification(item.specification) }}</td>
                  <td class="text-right">{{ item.isNew ? '-' : formatNumber(item.currentQuantity) }}</td>
                  <td class="text-right">
                    <input
                      v-model.number="item.newQuantity"
                      type="number"
                      class="form-input form-input-sm text-right"
                      min="0"
                      step="0.01"
                      @input="calculateDiff(item)"
                    />
                  </td>
                  <td class="text-right">
                    <span :class="getDiffClass(item)">
                      {{ getDiffText(item) }}
                    </span>
                  </td>
                  <td class="text-center">
                    <button
                      v-if="item.isNew"
                      type="button"
                      class="btn-remove"
                      @click="removeNewItem(item.skuId)"
                      title="삭제"
                    >
                      <i class="fas fa-trash-alt"></i>
                    </button>
                    <span v-else class="text-muted">-</span>
                  </td>
                </tr>
              </tbody>
              <tfoot>
                <tr class="total-row">
                  <td colspan="2" class="text-right"><strong>총 수량</strong></td>
                  <td class="text-right"><strong>{{ formatNumber(originalTotalQuantity) }}</strong></td>
                  <td class="text-right"><strong>{{ formatNumber(newTotalQuantity) }}</strong></td>
                  <td class="text-right">
                    <span :class="totalDiffClass">
                      <strong>{{ totalDiffText }}</strong>
                    </span>
                  </td>
                  <td></td>
                </tr>
              </tfoot>
            </table>
          </div>
        </div>

        <!-- 총 수량 경고 -->
        <div v-if="!isQuantityValid" class="warning-box">
          <i class="fas fa-exclamation-triangle"></i>
          <div>
            <strong>총 수량이 일치하지 않습니다</strong>
            <p>원래 총 수량({{ formatNumber(originalTotalQuantity) }})과 변경 후 총 수량({{ formatNumber(newTotalQuantity) }})이 같아야 합니다.</p>
          </div>
        </div>

        <!-- 변경 요약 -->
        <div v-if="hasChanges && isQuantityValid" class="summary-box">
          <i class="fas fa-info-circle"></i>
          <div>
            <span>{{ changeSummaryText }}</span>
            <div v-if="autoGeneratedLog" class="change-log-preview">
              <strong>변경 내역:</strong>
              <pre>{{ autoGeneratedLog }}</pre>
            </div>
          </div>
        </div>

        <!-- 서명 처리 방식 선택 (서명대기 상태일 때만 표시) -->
        <div v-if="isPendingSignature" class="form-section">
          <label class="form-label">서명 처리 방식</label>
          <div class="signature-options">
            <label class="signature-option" :class="{ active: reuseSignature }">
              <input
                v-model="reuseSignature"
                type="radio"
                name="signatureOption"
                :value="true"
              />
              <div class="option-content">
                <div class="option-title">
                  <i class="fas fa-redo"></i>
                  기존 서명 재사용
                  <span class="badge-recommended">권장</span>
                </div>
                <p class="option-description">
                  기존에 받은 서명으로 인수증을 새로 생성합니다.<br />
                  재서명 절차 없이 즉시 완료됩니다.
                </p>
              </div>
            </label>
            <label class="signature-option" :class="{ active: !reuseSignature }">
              <input
                v-model="reuseSignature"
                type="radio"
                name="signatureOption"
                :value="false"
              />
              <div class="option-content">
                <div class="option-title">
                  <i class="fas fa-pen"></i>
                  새로 서명 받기
                </div>
                <p class="option-description">
                  문자 발송 → 서명 → 사진 촬영 절차가 필요합니다.<br />
                  기존 서명/사진 정보가 초기화됩니다.
                </p>
              </div>
            </label>
          </div>
          <p class="signature-note">
            <i class="fas fa-history"></i>
            기존 인수증은 이력으로 보관됩니다.
          </p>
        </div>
      </div>

      <div class="modal-footer">
        <button class="btn-secondary" @click="closeModal">
          <i class="fas fa-times"></i>
          취소
        </button>
        <button
          class="btn-primary"
          :disabled="!canSubmit || isSubmitting"
          @click="handleSubmit"
        >
          <i v-if="isSubmitting" class="fas fa-spinner fa-spin"></i>
          <i v-else class="fas fa-check"></i>
          변경 적용
        </button>
      </div>
    </div>
  </div>

  <!-- SKU 선택 팝업 -->
  <ItemSkuSelector
    v-model="showSkuSelector"
    @sku-selected="handleSkuSelected"
  />
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import { formatNumber } from '~/utils/format'
import { shipmentService } from '~/services/shipment.service'
import type { AdditionalChangeItem, AdditionalChangeResponse } from '~/types/shipment-change'
import type { Item, ItemSku } from '~/services/item.service'
import ItemSkuSelector from '~/components/admin/ItemSkuSelector.vue'

// Props
interface ShipmentItem {
  skuId: string
  itemName: string
  specification?: string
  shipmentQuantity: number
  unitPrice?: number
  unit?: string
}

interface Props {
  isOpen: boolean
  shipmentId: number
  shipmentStatus: string
  items: ShipmentItem[]
}

const props = withDefaults(defineProps<Props>(), {
  items: () => [],
  shipmentStatus: ''
})

// Emits
const emit = defineEmits<{
  (e: 'close'): void
  (e: 'complete', response: AdditionalChangeResponse): void
}>()

// State
const changeReason = ref('')
const isSubmitting = ref(false)
const reuseSignature = ref(true)
const showSkuSelector = ref(false)

interface EditableItem {
  skuId: string
  itemName: string
  specification?: string
  currentQuantity: number
  newQuantity: number
  diff: number
  isNew: boolean
  unitPrice?: number
  unit?: string
}

const editableItems = ref<EditableItem[]>([])

// Computed
const isPendingSignature = computed(() => {
  return props.shipmentStatus === 'PENDING_SIGNATURE'
})

// 원래 총 수량 (기존 품목만)
const originalTotalQuantity = computed(() => {
  return editableItems.value
    .filter(item => !item.isNew)
    .reduce((sum, item) => sum + item.currentQuantity, 0)
})

// 변경 후 총 수량 (모든 품목)
const newTotalQuantity = computed(() => {
  return editableItems.value.reduce((sum, item) => sum + (item.newQuantity || 0), 0)
})

// 총 수량 차이
const totalDiff = computed(() => {
  return newTotalQuantity.value - originalTotalQuantity.value
})

// 신규 품목 존재 여부
const hasNewItems = computed(() => {
  return editableItems.value.some(item => item.isNew)
})

// 총 수량 일치 여부 (신규 품목이 있으면 검증 건너뜀)
const isQuantityValid = computed(() => {
  if (hasNewItems.value) return true  // 신규 품목 추가 시 검증 안 함
  return Math.abs(totalDiff.value) < 0.01
})

const totalDiffClass = computed(() => {
  if (Math.abs(totalDiff.value) < 0.01) return 'text-success'
  return 'text-danger'
})

const totalDiffText = computed(() => {
  if (totalDiff.value > 0) return `+${formatNumber(totalDiff.value)}`
  if (totalDiff.value < 0) return formatNumber(totalDiff.value)
  return '0'
})

const hasChanges = computed(() => {
  // 기존 품목 수량 변경 또는 신규 품목 추가
  return editableItems.value.some(item =>
    item.isNew || item.diff !== 0
  )
})

const changedItemCount = computed(() => {
  return editableItems.value.filter(item => item.isNew || item.diff !== 0).length
})

const newItemCount = computed(() => {
  return editableItems.value.filter(item => item.isNew).length
})

const modifiedItemCount = computed(() => {
  return editableItems.value.filter(item => !item.isNew && item.diff !== 0).length
})

const changeSummaryText = computed(() => {
  const parts: string[] = []
  if (newItemCount.value > 0) {
    parts.push(`${newItemCount.value}개 품목 추가`)
  }
  if (modifiedItemCount.value > 0) {
    parts.push(`${modifiedItemCount.value}개 품목 수량 변경`)
  }
  return parts.join(', ') + '됩니다.'
})

// 자동 생성된 변경 이력
const autoGeneratedLog = computed(() => {
  const logs: string[] = []

  // 신규 추가 품목
  editableItems.value
    .filter(item => item.isNew && item.newQuantity > 0)
    .forEach(item => {
      logs.push(`[추가] ${item.itemName} ${formatNumber(item.newQuantity)}${item.unit || 'm²'}`)
    })

  // 수량 감소 품목
  editableItems.value
    .filter(item => !item.isNew && item.diff < 0)
    .forEach(item => {
      logs.push(`[감소] ${item.itemName} ${formatNumber(item.currentQuantity)} → ${formatNumber(item.newQuantity)}${item.unit || 'm²'}`)
    })

  // 수량 증가 품목
  editableItems.value
    .filter(item => !item.isNew && item.diff > 0)
    .forEach(item => {
      logs.push(`[증가] ${item.itemName} ${formatNumber(item.currentQuantity)} → ${formatNumber(item.newQuantity)}${item.unit || 'm²'}`)
    })

  return logs.join('\n')
})

const canSubmit = computed(() => {
  return changeReason.value.trim() !== '' && hasChanges.value && isQuantityValid.value
})

// Methods
const closeModal = () => {
  emit('close')
}

const initializeItems = () => {
  editableItems.value = props.items.map(item => ({
    skuId: item.skuId,
    itemName: item.itemName,
    specification: item.specification,
    currentQuantity: item.shipmentQuantity,
    newQuantity: item.shipmentQuantity,
    diff: 0,
    isNew: false,
    unitPrice: item.unitPrice,
    unit: item.unit
  }))
}

const calculateDiff = (item: EditableItem) => {
  if (item.isNew) {
    item.diff = item.newQuantity
  } else {
    item.diff = item.newQuantity - item.currentQuantity
  }
}

const getDiffClass = (item: EditableItem): string => {
  if (item.isNew) return 'text-primary'
  if (item.diff > 0) return 'text-success'
  if (item.diff < 0) return 'text-danger'
  return 'text-muted'
}

const getDiffText = (item: EditableItem): string => {
  if (item.isNew) return `+${formatNumber(item.newQuantity)}`
  if (item.diff > 0) return `+${formatNumber(item.diff)}`
  if (item.diff < 0) return formatNumber(item.diff)
  return '0'
}

// 규격에서 첫 번째 콤마 이후 부분만 표시 (품목명 제외)
const formatSpecification = (spec: string | undefined): string => {
  if (!spec) return '-'
  const commaIndex = spec.indexOf(',')
  if (commaIndex === -1) return spec
  return spec.substring(commaIndex + 1).trim()
}

// SKU 선택 팝업 열기
const openSkuSelector = () => {
  showSkuSelector.value = true
}

// SKU 선택 완료
const handleSkuSelected = (item: Item, sku: ItemSku) => {
  // 이미 추가된 SKU인지 확인
  const existingIndex = editableItems.value.findIndex(i => i.skuId === sku.skuId)
  if (existingIndex !== -1) {
    alert('이미 추가된 품목입니다.')
    return
  }

  // 규격 문자열 생성
  const specParts: string[] = []
  if (item.itemNm) specParts.push(item.itemNm)
  if (sku.skuNm) specParts.push(sku.skuNm)
  if (sku.width) specParts.push(`${sku.width}mm`)
  if (sku.height) specParts.push(`${sku.height}mm`)
  if (sku.thickness) specParts.push(`${sku.thickness}T`)

  // 신규 품목 추가
  editableItems.value.push({
    skuId: sku.skuId,
    itemName: item.itemNm,
    specification: specParts.join(', '),
    currentQuantity: 0,
    newQuantity: 0,
    diff: 0,
    isNew: true,
    unitPrice: sku.unitPrice,
    unit: 'm²'
  })

  showSkuSelector.value = false
}

// 신규 품목 삭제
const removeNewItem = (skuId: string) => {
  const index = editableItems.value.findIndex(item => item.skuId === skuId && item.isNew)
  if (index !== -1) {
    editableItems.value.splice(index, 1)
  }
}

const handleSubmit = async () => {
  if (!canSubmit.value || isSubmitting.value) return

  isSubmitting.value = true

  try {
    // 변경된 품목만 필터링
    const changedItems: AdditionalChangeItem[] = editableItems.value
      .filter(item => item.isNew || item.diff !== 0)
      .map(item => ({
        skuId: item.skuId,
        currentQuantity: item.currentQuantity,
        newQuantity: item.newQuantity,
        isNew: item.isNew,
        unitPrice: item.unitPrice,
        itemName: item.itemName,
        specification: item.specification,
        unit: item.unit
      }))

    // 변경 사유에 자동 생성된 로그 추가
    const fullChangeReason = autoGeneratedLog.value
      ? `${changeReason.value.trim()}\n\n[변경 내역]\n${autoGeneratedLog.value}`
      : changeReason.value.trim()

    // 서명대기 상태일 때만 reuseSignature 전달
    const requestData = {
      shipmentId: props.shipmentId,
      items: changedItems,
      changeReason: fullChangeReason,
      ...(isPendingSignature.value && { reuseSignature: reuseSignature.value })
    }

    const response = await shipmentService.executeAdditionalChange(requestData)

    if (response.success) {
      emit('complete', response)
    } else {
      alert(response.errorMessage || '추가변경에 실패했습니다.')
    }
  } catch (error) {
    console.error('추가변경 실패:', error)
    alert('추가변경 중 오류가 발생했습니다.')
  } finally {
    isSubmitting.value = false
  }
}

// Watch
watch(() => props.isOpen, (isOpen) => {
  if (isOpen) {
    changeReason.value = ''
    reuseSignature.value = true
    initializeItems()
  }
})
</script>

<style scoped>
@import '@/assets/css/admin-common.css';
@import '@/assets/css/admin-buttons.css';

.modal-overlay {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(0, 0, 0, 0.5);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 1000;
}

.modal {
  background: white;
  border-radius: 12px;
  box-shadow: 0 10px 40px rgba(0, 0, 0, 0.2);
  max-height: 90vh;
  overflow-y: auto;
}

.modal-large {
  width: 90%;
  max-width: 900px;
}

.modal-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 1.25rem 1.5rem;
  border-bottom: 1px solid #e5e7eb;
}

.modal-header h3 {
  margin: 0;
  font-size: 1.25rem;
  font-weight: 600;
  color: #1f2937;
}

.modal-close {
  background: none;
  border: none;
  font-size: 1.25rem;
  color: #6b7280;
  cursor: pointer;
  padding: 0.5rem;
  border-radius: 6px;
  transition: all 0.2s;
}

.modal-close:hover {
  background: #f3f4f6;
  color: #374151;
}

.modal-body {
  padding: 1.5rem;
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
}

.modal-footer {
  display: flex;
  justify-content: flex-end;
  gap: 0.75rem;
  padding: 1.25rem 1.5rem;
  border-top: 1px solid #e5e7eb;
  background: #f9fafb;
}

/* 섹션 헤더 */
.section-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 0.5rem;
}

.btn-add-item {
  display: inline-flex;
  align-items: center;
  gap: 0.375rem;
  padding: 0.5rem 0.875rem;
  background: #10b981;
  color: white;
  border: none;
  border-radius: 6px;
  font-size: 0.8125rem;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.2s;
}

.btn-add-item:hover:not(:disabled) {
  background: #059669;
}

.btn-add-item:disabled {
  background: #9ca3af;
  cursor: not-allowed;
  opacity: 0.6;
}

/* 경고 박스 */
.warning-box {
  display: flex;
  align-items: flex-start;
  gap: 0.75rem;
  padding: 1rem;
  background: #fef3c7;
  border: 1px solid #f59e0b;
  border-radius: 8px;
  color: #92400e;
}

.warning-box i {
  font-size: 1.25rem;
  color: #f59e0b;
  margin-top: 0.125rem;
}

.warning-box strong {
  display: block;
  margin-bottom: 0.25rem;
}

.warning-box p {
  margin: 0;
  font-size: 0.875rem;
}

/* 폼 섹션 */
.form-section {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}

.form-label {
  font-weight: 600;
  color: #374151;
  font-size: 0.875rem;
}

.form-label.required::after {
  content: ' *';
  color: #dc2626;
}

.form-textarea {
  width: 100%;
  padding: 0.75rem;
  border: 1.5px solid #d1d5db;
  border-radius: 6px;
  font-size: 0.875rem;
  resize: vertical;
  transition: border-color 0.2s;
}

.form-textarea:focus {
  outline: none;
  border-color: #2563eb;
}

/* 테이블 */
.table-container {
  overflow-x: auto;
}

.data-table {
  width: 100%;
  border-collapse: collapse;
  font-size: 0.875rem;
}

.data-table th {
  padding: 0.5rem 0.75rem;
  text-align: center;
  background: #f9fafb;
  font-weight: 600;
  color: #374151;
  border-bottom: 2px solid #e5e7eb;
  white-space: nowrap;
}

.data-table td {
  padding: 0.5rem 0.75rem;
  border-bottom: 1px solid #f3f4f6;
  text-align: center;
}

.data-table tfoot td {
  padding: 0.75rem;
  background: #f9fafb;
  border-top: 2px solid #e5e7eb;
}

/* 신규 품목 행 */
.new-item-row {
  background: #ecfdf5;
}

.badge-new {
  display: inline-flex;
  align-items: center;
  padding: 0.125rem 0.375rem;
  background: #10b981;
  color: white;
  font-size: 0.625rem;
  font-weight: 600;
  border-radius: 4px;
  margin-right: 0.375rem;
}

/* 컬럼별 너비 및 정렬 */
.col-item-name {
  width: 120px;
  min-width: 120px;
  text-align: left !important;
}

.col-spec {
  width: 280px;
  max-width: 280px;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.col-spec.col-spec-header {
  text-align: center !important;
}

td.col-spec {
  text-align: left !important;
}

.col-quantity {
  width: 90px;
  text-align: right !important;
}

.col-diff {
  width: 70px;
  text-align: right !important;
}

.col-action {
  width: 50px;
  text-align: center !important;
}

.data-table td.text-right {
  text-align: right !important;
}

.data-table td.text-center {
  text-align: center !important;
}

.form-input-sm {
  width: 80px;
  padding: 0.375rem 0.5rem;
  border: 1.5px solid #d1d5db;
  border-radius: 4px;
  font-size: 0.8125rem;
}

.form-input-sm:focus {
  outline: none;
  border-color: #2563eb;
}

/* 삭제 버튼 */
.btn-remove {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 28px;
  height: 28px;
  background: #fee2e2;
  color: #dc2626;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  transition: all 0.2s;
}

.btn-remove:hover {
  background: #fecaca;
}

/* 총 수량 행 */
.total-row td {
  font-weight: 600;
}

/* 색상 클래스 */
.text-success {
  color: #059669;
  font-weight: 500;
}

.text-danger {
  color: #dc2626;
  font-weight: 500;
}

.text-primary {
  color: #2563eb;
  font-weight: 500;
}

.text-muted {
  color: #9ca3af;
}

/* 요약 박스 */
.summary-box {
  display: flex;
  align-items: flex-start;
  gap: 0.5rem;
  padding: 0.75rem 1rem;
  background: #eff6ff;
  border-radius: 6px;
  color: #1e40af;
  font-size: 0.875rem;
}

.summary-box i {
  color: #3b82f6;
  margin-top: 0.125rem;
}

.change-log-preview {
  margin-top: 0.5rem;
  padding: 0.5rem;
  background: white;
  border-radius: 4px;
  font-size: 0.8125rem;
}

.change-log-preview strong {
  display: block;
  margin-bottom: 0.25rem;
  color: #374151;
}

.change-log-preview pre {
  margin: 0;
  font-family: inherit;
  white-space: pre-wrap;
  color: #6b7280;
}

/* 버튼 */
.btn-primary,
.btn-secondary {
  display: inline-flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.75rem 1.25rem;
  border-radius: 6px;
  font-size: 0.875rem;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.2s;
}

.btn-primary {
  background: #2563eb;
  color: white;
  border: none;
}

.btn-primary:hover:not(:disabled) {
  background: #1d4ed8;
}

.btn-primary:disabled {
  background: #93c5fd;
  cursor: not-allowed;
}

.btn-secondary {
  background: white;
  color: #374151;
  border: 1px solid #d1d5db;
}

.btn-secondary:hover {
  background: #f9fafb;
}

/* 서명 처리 방식 옵션 */
.signature-options {
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
}

.signature-option {
  display: flex;
  align-items: flex-start;
  gap: 0.75rem;
  padding: 1rem;
  border: 1.5px solid #e5e7eb;
  border-radius: 8px;
  cursor: pointer;
  transition: all 0.2s;
  background: white;
}

.signature-option:hover {
  border-color: #93c5fd;
  background: #f8fafc;
}

.signature-option.active {
  border-color: #2563eb;
  background: #eff6ff;
}

.signature-option input[type="radio"] {
  margin-top: 0.25rem;
  accent-color: #2563eb;
  width: 16px;
  height: 16px;
  cursor: pointer;
}

.option-content {
  flex: 1;
}

.option-title {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  font-weight: 600;
  color: #1f2937;
  font-size: 0.9375rem;
  margin-bottom: 0.375rem;
}

.option-title i {
  color: #6b7280;
  font-size: 0.875rem;
}

.signature-option.active .option-title i {
  color: #2563eb;
}

.badge-recommended {
  display: inline-flex;
  align-items: center;
  padding: 0.125rem 0.5rem;
  background: #dcfce7;
  color: #15803d;
  font-size: 0.6875rem;
  font-weight: 600;
  border-radius: 4px;
  text-transform: uppercase;
}

.option-description {
  margin: 0;
  font-size: 0.8125rem;
  color: #6b7280;
  line-height: 1.5;
}

.signature-note {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  margin: 0.75rem 0 0 0;
  padding: 0.5rem 0.75rem;
  background: #fef3c7;
  border-radius: 6px;
  font-size: 0.8125rem;
  color: #92400e;
}

.signature-note i {
  color: #f59e0b;
}
</style>
